first_project/urls.py
from django.contrib import admin
from django.urls import include, path
# from polls.views import index
# from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls'))
    # or directly the function from view ie index can be added here as=>
    # path('anyname',index)
]

polls/urls.py
from django.urls import path
from . import views
# from polls.views import index

app_name = 'polls'  # adding namespace


urlpatterns=[path('', views.index,name='index'),
            path('<int:question_id>/',views.detail,name='detail'),
            path('<int:question_id>/results/',views.results,name='results'),
            path('<int:question_id>/vote/',views.vote,name='vote')
]
             # path('',views.example)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text= models.CharField(max_length=200)
    pub_date= models.DateTimeField('date published')

    def __str__(self):  #ie whenever print func will b used for this type of object it will print the value returned by this __str__ func.
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()

datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes= models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render  #either this or above line

# Create your views here.



def index(request):
    # return HttpResponse("heya! You're at the polls index")
    latest_question_list = Question.objects.order_by('-pub_date')[:5]   #tutorial 3

    # output = ', '.join([q.question_text for q in latest_question_list])
    # -->template = loader.get_template('polls/index.html')

    context={'latest_question_list':latest_question_list,}
    #its like a dictionary with key and value


    # -->return HttpResponse(template.render(context,request))
    # --> (replacing those) with below line using shortcut render()
    return render(request,'polls/index.html',context)
    #theory:The render() function takes the request object as its
    # first argument, a template name as its second argument and a
    # dictionary as its optional third argument. It returns an HttpResponse object of the given template rendered with the given context.




def detail(request,question_id):
    # return HttpResponse("you're looking at question %s." % question_id)


    # or to generate Http404 error if the requested id isnt present
    # 1st method

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # return render(request,'polls.detail.html',{'question':questions})

    # # or 2nd shortcut method
    # import get_object_or_404,render

    question = get_object_or_404(Question, pk=question_id)
    return render(request,'polls/details.html', {'question':question})



def results(request, question_id):
    response = "you're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request,question_id):
    return HttpResponse("you're voting on question %s."% question_id)

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <!--interpreted as pyth code question.choice_set.all()--
    which returns an iterable of choice objs suitable for use in {% for %}tag-->

  <li>{{ Choice.choice_text }}</li>
  {% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}


        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->

        <!-- this partially hardcoded urls can be replaced by {% url %} tag -->
        <!--since name arguments has been defined in path fun in polls.urls,
          so u can remove a reliance on specific URL paths in your url confs by using
          {% url %}tag-->

          <li><a href="{% url 'polls:detail' question.id}"></a>{{ question.question_text}}</li>
          <!--polls:detail -- polls specifies namespace  -->

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}